# -*- coding: utf-8 -*-
"""steps.ipynb

Automatically generated by Colaboratory.

Original file is located at
	https://colab.research.google.com/drive/1tso8cPapISSKDFFW7SKaBQjRcCJHCQYm
"""

import numpy as np

print("SERGIO:")
for x in range(1,20):
	n = x
	m = int(np.floor(n/2))

	steps = n # 1 way, placing all ones, + (n-1) ways, placing all twos

	for i in range(2,m+1,1): # it should include m, in Python the range is defined until m+1
		for j in range(2*(i-1),n-1,1): # it should include the value n-2, in Python the range is defined until n-1
			steps = steps + n - j - 1

	print("n="+str(x) + " sol=" + str(steps))

